### PR TITLE
samuel/feat/mac support

### PR DESCRIPTION
**Pull request by samuelhimmelstrup**
- Create jenkinsfile for CI/CD (#69)
- devops: npm audit fix 1 dep
- devops: npm script pyinstall will remove existing python-venv environment
- fix: throw errors if trying to upload empty files
- feat: add rowsPrCrop temporary context menu item
- feat: add all scrollshot settings to context menu
- chore(version): bump to v1.0.6
- fix: make  pyfreeze* scripts and pythonBridge compatible + typo in README
- fix: warn if screen is not accessible (for macOS)
- fix: screenshot fix for macOS
- add macOS system preferences guide + add myself as contributor
- fix: forge DMG maker settings + remove unused devDeps

### CODE REVIEW

**Comment by samuelhimmelstrup** [comment]
Rebased unstable into this branch, so now has no merge conflicts 👍  !
This PR contains changes from #76.

**Comment by nikobojs** [comment]
All right, crazy PR !!! ManuScrape on Mac is basically working now

**Comment by nikobojs** [comment]
Please add your self to the contributor list in your next PR ;-)

**Comment by nikobojs** [comment]
@samuelhimmelstrup @bjarke22 Users are asking for the Mac version :p If you want to help, it would be greatly appreciated by all of the manuscrape community as well as many students in danish universities.

In other words, you'll get lots of free beer in CPH from me and others, if one of you compile and code sign the next couple of ManuScrape Electron versions (until I can automate it with a mac mini thing I'll buy when I have the money).

Of course, any one is welcome to contribute :pray:

**Pull request merged**
